language: rust
cache: cargo
dist: trusty
os:
  - linux
  - osx
rust:
  - nightly
  - stable

before_script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        which rustfmt || cargo install rustfmt-nightly
      fi
  - export PATH=$PATH:~/.cargo/bin

script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        cargo fmt -- --write-mode=diff
      fi
  - cargo build
  - cargo test
