dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=scout

matrix:
  include:
    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1

    # Nightly channel
    - env: TARGET=x86_64-unknown-linux-gnu ENABLE_CLIPPY=1
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install: set -e

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: ir9VZgyy4pCRYUWA32PlqKGEXz43vl7T3u3t3yvXZHW+QR18SPJBHpjXh64ieG2WedSUvGio6ABEzLgv2XVDaQt6ValdoA/pG7hOVMc/ecALWsmVnXc+7zrGob7t5EBBnDAD4SeCv8X1S4XAWFZayOGYOZ88ka4GYFwwuVvErhx0C+bJ9qK0CKly56BQLME/IY2TqqCvRCLaJ3rIyzNo1bbp2t5b7KKCt4bq7fGG534QouG62ODNx18IssFrlXb2Q44jD7HX+1Awxe8djIbhcSwt51Nhvhr743UNKlYyUHw0IiozU/vviA5dbFO7kF/G0OGk1EXpSGMTjbfEsEi4e2bn7Jj/0d5OxwX31Qf0/zDiCr5c9Wu+/B3XkbkARqTYto1kQSCu7O4VjKr08CeZQmmcE8WeiOA0pCcqbc50P0jUWeyDnzN6wmUCzLaE9S+J6QyUA3D4iAkrHQ/xNRVNtErd70BOqWW7xoR/2Z3KNPXd29C4GzIT+rUPuBS6R04op7h1DrWq6nxSbYRSxilfBXOp3893fumGAr+yqO3voKLQFkTIy/kCAQQ9EVIMDFqTOFOeReRjBDI0TIZgZXQAJeDAcOGgnF6QLCdVIk46xKQbNKpPSl6NRy1+GXjNhMv0dV29OsBhzqy77E058kI/A+SdgfQckgyk375kkgNnYhE=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true
