[package]
name = "scout"
version = "0.9.2"
authors = ["Juan Hernández <juan.hernandez.babon@gmail.com>"]
description = "Small fuzzy finder for the command line"
homepage = "https://github.com/jhbabon/scout"
repository = "https://github.com/jhbabon/scout"
readme = "README.md"
keywords = ["scout", "fuzzy", "fuzzyfinder", "cli"]
license = "MIT"

[lib]
name = "scout"
path = "src/scout/lib.rs"

[[bin]]
name = "scout"
path = "src/bin.rs"
doc = false

[dependencies]
termios = "0.2"
termion = "1.3"
regex = "0.2"
docopt = "0.7"
libc  = "0.2.21"
num_cpus = "1.5"
futures = "0.1"
futures-cpupool = "0.1"
