[package]
name = "scout"
version = "2.0.0-alpha"
authors = ["Juan Hernández <juan.hernandez.babon@gmail.com>"]
description = "Small fuzzy finder for the command line"
homepage = "https://github.com/jhbabon/scout"
repository = "https://github.com/jhbabon/scout"
readme = "README.md"
keywords = ["scout", "fuzzy", "fuzzyfinder", "cli"]
license = "MIT"
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.19", features = [ "async-await" ] }
async-std = "0.99"
termios = "0.3.1"
termion = "1.5.3"
log = "0.4.8"
env_logger = "0.7.0"
rayon = "1.2.0"
